### ISSUE TITLE
Localization not working with Underground Biomes Constructs

### ISSUE THREAD

**Issue by Adaptivity** [TeamMetallurgy/Metallurgy4#49]
Metallurgy ore name: http://i.imgur.com/FOkmHEf.jpg
Vanilla ore name: http://i.imgur.com/sdELmEt.jpg
Vanilla name have no .name at the end of the name. And also vanilla name can use different localization names but Metallurgy ore remains in English always.

**Comment by Adaptivity** [comment]
Thanks!

**Comment by Glassmaker** [comment]
you're welcome :)
