### ISSUE TITLE
Cannot Craft Copper/Bronze Bricks in Crackpack 2.x

### ISSUE THREAD

**Issue by Mochnant** [TeamMetallurgy/Metallurgy4#54]
I'm unable to craft Copper Bricks or Bronze Bricks in Crackpack 2.0.3.0 (latest).  While I know this is likely a conflict in the pack itself, I thought Team Metallurgy might have an idea why, as I haven't had much success (yet) with the mod angle.

My Crackpack bug report for this same issue is at https://github.com/sciguyryan/TheCrackPack/issues/749

Thanks for the help.

**Comment by odininon** [comment]
Just these two bricks?

**Comment by odininon** [comment]
@Glassmaker looks like https://github.com/TeamMetallurgy/Metallurgy4/blob/a947e1b082528accc64bc78dea04c14c50193228/src/main/java/com/teammetallurgy/metallurgy/metals/MetalSet.java#L522 Might be the cuplrit.

**Comment by Mochnant** [comment]
@odininon Thanks for looking into it!  I did not make an exhaustive analysis of all M4 brick types, other than to confirm that some worked and some didn't (the ones I recall were gold worked, copper/bronze did not).  There are likely more that are also broken.

**Comment by Mochnant** [comment]
@odininon As a followup, and for my own knowledge, what's the issue with that line of code?

`GameRegistry.addShapedRecipe(new ItemStack(brick, 1, metaId), new Object[] { "ii", "ii", 'i', ingot });`

**Comment by Glassmaker** [comment]
Nothing wrong with that one, maybe it's disabled in the pack as it conflicts with another mod
wait for reply from the modpack author.

![2015-01-10_22 34 54](https://cloud.githubusercontent.com/assets/5352172/5692917/1450b98a-9919-11e4-91dd-060476da93d2.png)

![2015-01-10_22 35 47](https://cloud.githubusercontent.com/assets/5352172/5692918/145611a0-9919-11e4-8b34-e22a019cac2f.png)
