### ISSUE TITLE
Worlds can't be loaded/created when Thermal Expansion is present, but the issue seems to come from Metallurgy

### ISSUE THREAD

**Issue by AegisLesha** [TeamMetallurgy/Metallurgy4#58]
All the details are here:
https://github.com/CoFH/Feedback/issues/158#issuecomment-75463001

**Comment by Glassmaker** [comment]
Interesting,
Metallurgy doesn't touch TE's Pulverizer, so I'm guessing it's AOBD as it have Thermal Expansion support.
Try it without AOBD and check if it breaks.

**Comment by Adaptivity** [comment]
I have both Metallurgy and AOBD in my pack with latest TE and I have no problems. Remove all mods and try adding them by batches until crash happens.

**Comment by Glassmaker** [comment]
Closing the issue, as no further information was provide for more than 2 weeks.
