### ISSUE TITLE
Vanilla "secondary" enchants available via enchanting table

### ISSUE THREAD

**Issue by Fickilty** [TeamMetallurgy/Metallurgy4#64]
According to the Minecraft wiki's "enchanting" page, enchantments are only obtainable on secondary items via an enchanted book + anvil.

However I just put a Tartarite axe in an enchanting table, with 30 levels, and got Bane of Arthropods. For vanilla, the primary item for Bane of Arthropods is a sword, and axes are secondary, so the only way to get Bane of Arthropods on (vanilla) axes is with an enchanted book and an anvil. Not for Tartarite (and I assume all Metallurgy axes) though.

**Comment by Glassmaker** [comment]
![2015-05-29_19 47 26](https://cloud.githubusercontent.com/assets/5352172/7887729/e76fbcf0-063b-11e5-8f5b-c1d5c4f9609e.png)

Umm... guess it's not Metallurgy's problem.

Looking though the code, Bane of Arthropods is only marked for weapons, in this case the sword.

Either some mod changed the behaviour or a forge bug I missed.
