### ISSUE TITLE
Question : Metallurgy bees ? :/

### ISSUE THREAD

**Issue by quienti** [TeamMetallurgy/Metallurgy4#69]
Hi !

Have you planned to update Mettalurgy Bees with Forestry and Mettalurgy or this mod is dead ? :/

Thank you

**Comment by Glassmaker** [comment]
Metallurgy bees is on the plan.
There will be an announcement when it's released :)

**Comment by quienti** [comment]
Nice :D

Thank you for your response :)

**Comment by quienti** [comment]
https://github.com/TeamMetallurgy/Metallurgy-Bees/pull/6

What do you think? :)

**Comment by Glassmaker** [comment]
Pulled in, thanks again :)
closing this one too :)
