### ISSUE TITLE
Metallurgy items - Fatally missing blocks and items (OS Language problem)

### ISSUE THREAD

**Issue by cemakd** [TeamMetallurgy/Metallurgy4#70]
When I try to connect to my friends multiplayer server or start up a map of my own in the Modpack Blightfall, I get an error stating that 51 of the items/blocks are missing from the Metallurgy mod. 

Through research on the internet I found that this might be caused because of my Operating System being in Turkish language. Since the capital "i" is written as İ (I with a dot at top) every item in the mod that has a word which starts with a capital I is not recognized by the game. Couple suggestions included writing Java Args to the launchers settings which are:
-Duser.language=en
-Duser.country=US
But these didnt change anything.

So my last option came down to asking for help from the mod developers here. If you can assist me with this issue it would be greatly appreciated. If you need any additional info, I can also provide it. Thanks a lot!

Here is the error I get when I'm creating a single player world:
![image](https://cloud.githubusercontent.com/assets/15164133/10651664/f1b8b126-781e-11e5-8c1b-aff18da4e290.png)

**Comment by Glassmaker** [comment]
Should be fixed with 529f0820e95cc9cc32ebdca109ae9fd0753504b7, closing the issue :)
