### ISSUE TITLE
Can't put Metallurgy molten metal buckets in ANY tank

### ISSUE THREAD

**Issue by kd8lvt** [TeamMetallurgy/Metallurgy4#72]
Tested with Sanguinite, not sure it other molten metals are affected. The liquid visually goes in, but when the visuals are refreshed / chunk is reloaded, it dissapears. In fact, the whole bucket of liquid is deleted. You keep the empty bucket, but the liquid is gone. Tested with both Open Blocks tanks and Thermal Expansion portable tanks. Latest version of metallurgy, within Project Ozone pack.

--EDIT--
You can't put it into a TE tank, OB tanks accept it, but it gets deleted.
--EDIT 2--
I think this bug is caused by Fluid Cows making phantom buckets. Sorry!

**Comment by Glassmaker** [comment]
Hi @kd8lvt,

I have tested Sanguinite buckets from FluidMoo cows and I'm unable to recreate the issue in the Project Ozone pack.

I have tried reloading the visuals (F3 + A), closing the game, and moving away from the tanks then returning, the fluids are still there and don't vanish.

Are there more information you can provide to help identify the issue, like the is issue happening on server or you have extra mods installed that aren't in the pack?

**Comment by kd8lvt** [comment]
Hey @Glassmaker,

I don't have any extra mods, and I'm not on a server. I don't think graphics settings would change anything (Though I have smooth lighting off, particles off, and vsync off with a render distance of 8 chunks)

Thanks, Kd

**Comment by Glassmaker** [comment]
Hi @kd8lvt ,

Yeah, couldn't replicate that with the video settings.

Ummm.. Make sure that pack version in use is up to date, I have tested on Project OZone 1.3 beta 2 fixed.

**Comment by kd8lvt** [comment]
Well, if its fixed in the latest version of the pack, then i guess we don't have to worry about it, I completely forgot that it had an update, sorry about the waste of time >.> Feel free to close the issue :)
~Kd

**Comment by Glassmaker** [comment]
Okeo, closing the issue.

If it re-appears let me know :)
